url: 
baseurl: 

# Site settings
title: Junoon
email: nsit.junoon@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Paras Sain
  pic: 1
  position: Senior Coordinator
  social:
    - title: instagram
      url: https://www.instagram.com/theframeist/
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Mayukh Chatterjee
  pic: 2
  position: Nalla
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Mehul Sharma
  pic: 3
  position: Event Head
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #


      # Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/junoon.nsut/
  - title: facebook
    url: https://www.facebook.com/junoon.nsut/
  - title: youtube
    url: http://youtube.com/user/junoon.broadcast

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty